### ISSUE TITLE
Concentration vs. time

### ISSUE THREAD

**Issue by mkrompiec** [tongzhugroup/reacnetgenerator#1069]
How hard would it be to implement a "concentration" (actually, count) vs. time plot for each species? I guess the .species file cannot be used for this purpose, can it?

**Comment by z5476t4508** [comment]
Sorry for the late reply. Actually, the .species file already stores the number of each species.

**Comment by mkrompiec** [comment]
Thanks. So what I'm seeing is a result of a bug (or my misunderstanding of the HMM filter)
[test.zip](https://github.com/tongzhugroup/reacnetgenerator/files/6227459/test.zip)
. I run reacnetgenerator on the attached file (few snapshots from a MD trajectory) like this: 
reacnetgenerator -i test.xyz -a Mo H S Cl -n 1 --nopbc --type xyz
The species file doesn't contain all the species in the system:
Timestep 0: [H]S[H] 7
Timestep 1: [H]S[H] 7
Timestep 2: [H]S[H] 4

But if I run it with the HMM filter disabled, all the species are properly detected:
reacnetgenerator -i test.xyz -a Mo H S Cl -n 1 --nopbc --type xyz --nohmm
Timestep 0: [H][SH]([H])[Mo](Cl)(Cl)(Cl)[Mo](Cl)(Cl)(Cl)[SH]([H])[H] 1 [H]S[H] 8
Timestep 1: [H]S[H] 7 [H][SH]([H])[Mo](Cl)(Cl)[Mo](Cl)(Cl)(Cl)(Cl)[SH]([H])[H] 1 [H]S 1 [HH] 1
Timestep 2: [H]S[H] 8 [H]S[Mo](Cl)(Cl)(Cl)[Mo](Cl)(Cl)[SH]([H])[H] 1 [H]Cl 1

**Comment by njzjz** [comment]
This is indeed an expected behavior instead of a program bug...  The species number is "real" when the HMM filter disabled, but it may be influenced when you use the HMM filter. This is the side effect of HMM filter, and it can be controlled by adjusting the parameters. (But in my experience, I will suggest to turn off the HMM filter when you just want to get the real number)
